// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaBs2FoNlXQkQK_Z6huUpCHJO563IztBY',
    appId: '1:200757979354:web:e01c1d6113ad845a0c5de3',
    messagingSenderId: '200757979354',
    projectId: 'borrow-app-cc43d',
    authDomain: 'borrow-app-cc43d.firebaseapp.com',
    storageBucket: 'borrow-app-cc43d.appspot.com',
    measurementId: 'G-BGZ9FGM5XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdTJ5QmdzbS8xCxcsjND4WNB_vJ_dmnDE',
    appId: '1:200757979354:android:2f94574907b841240c5de3',
    messagingSenderId: '200757979354',
    projectId: 'borrow-app-cc43d',
    storageBucket: 'borrow-app-cc43d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8fh3oNazOyilb6bnf9E3T9n8vQaMt7-0',
    appId: '1:200757979354:ios:94b3e46b221b28210c5de3',
    messagingSenderId: '200757979354',
    projectId: 'borrow-app-cc43d',
    storageBucket: 'borrow-app-cc43d.appspot.com',
    iosClientId: '200757979354-06qi7tuql351mvsu4254ehjau3nvvga3.apps.googleusercontent.com',
    iosBundleId: 'com.example.borrowult',
  );
}
